//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioCrecePlus
{
    using System;
    using System.Collections.Generic;
    
    public partial class Items
    {
        public int id_item { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public string sku { get; set; }
        public Nullable<int> id_tipopapel { get; set; }
        public Nullable<int> id_categoria { get; set; }
        public Nullable<int> id_medida { get; set; }
        public Nullable<bool> activo { get; set; }
    }
}
