//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioCrecePlus
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productos
    {
        public int id_producto { get; set; }
        public Nullable<int> cantidadordenada { get; set; }
        public string sku { get; set; }
        public int orden_numero { get; set; }
        public string especificacion { get; set; }
    
        public virtual Ordenes Ordenes { get; set; }
    }
}
