//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contador
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ordenes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ordenes()
        {
            this.OrdenItems = new HashSet<OrdenItems>();
        }
    
        public int OrdenID { get; set; }
        public string Status { get; set; }
        public string TipoTarjetaCredito { get; set; }
        public string MetodoEnvio { get; set; }
        public string Subtotal { get; set; }
        public string Impuesto { get; set; }
        public string CostoEnvio { get; set; }
        public string Descuento { get; set; }
        public string Total { get; set; }
        public Nullable<int> ClienteID { get; set; }
        public Nullable<System.DateTime> FechaOrden { get; set; }
        public string MetodoPago { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdenItems> OrdenItems { get; set; }
    }
}
