//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contador
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ordenes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ordenes()
        {
            this.Productos = new HashSet<Productos>();
        }
    
        public int orden_numero { get; set; }
        public Nullable<System.DateTime> fechaorden { get; set; }
        public Nullable<int> id_cliente { get; set; }
        public string metodo_envio { get; set; }
        public string metodo_pago { get; set; }
        public string tipo_tarjeta_credito { get; set; }
        public string costo_envio { get; set; }
        public string subtotal { get; set; }
        public string impuesto { get; set; }
        public string total { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Productos> Productos { get; set; }
    }
}
