//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contador
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenItems
    {
        public int OrdenItemID { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public string Costo { get; set; }
        public string Impuesto { get; set; }
        public string Total { get; set; }
        public string Descuento { get; set; }
        public Nullable<int> OrdenID { get; set; }
        public Nullable<int> ItemID { get; set; }
        public string Especificacion { get; set; }
    
        public virtual Items Items { get; set; }
        public virtual Ordenes Ordenes { get; set; }
    }
}
