//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contador
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductosPliego
    {
        public int id_producto { get; set; }
        public Nullable<int> copiasporpliego { get; set; }
        public Nullable<int> id_pliego { get; set; }
    
        public virtual Pliegos Pliegos { get; set; }
        public virtual Productos Productos { get; set; }
    }
}
